### ISSUE TITLE
TriEdgeCollapseQuadric is extremely slow

### ISSUE THREAD

**Issue by cdcseacave** [cnr-isti-vclab/vcglib#12] opened 2017-01-19 05:54 UTC
The latest VCG release has a bug in the TriEdgeCollapseQuadric simplification algorithm that causes the process to get extremely slow. The simplification finishes but instead of taking for example ~2min (normal time), it takes 15hours. This issue manifests both on windows and linux, and it appeared sometime after MeshLab version 1.3.3.

If needed, I have a mesh to reproduce the problem (but is around 450MB), but I think any big mesh will do it.

**Comment by cdcseacave** [comment] 2017-01-19 05:55
Doing some more investigations, it seems like the heap structure used during simplification grows exponentially, and after a while any operation in that heap structure take a lot of time.

**Comment by cignoni** [comment] 2017-02-15 13:52
I am on it. I have identified the problem. Testing it before committing. It is related to an error on the management of flat areas.  It can be replicated easily inside MeshLab: take a cube, refine using midpoint refine 6~7 times up to having a 700k tri mesh with large planar, finely tessellated surfaces. 
if you check the 'planar simplification' it works, but if you do not check that options it hangs forever.

**Comment by cdcseacave** [comment] 2017-02-15 19:27
Speaking about that option, what is it suppose to do exactly?

I was hoping it will identify planar areas and decimate them more, but it
seem not to do that; compared with the normal algorithm it produces more
uniform decimation (really the opposite).

**Comment by cignoni** [comment] 2017-02-15 21:28
Actually yes, that option makes the simplification on flat area much less drastic. This usually leads to a slightly less compact representations (in terms of numbers of triangles vs approximation error), but with much better characteristics in terms of triangle distribution and aspect ratio. 
In many cases this is a better choice. 

BTW that was a workaround for current version. The issue is going to be fixed without requiring checking that option.

**Closed** 2017-02-21 17:33 UTC
